# Use an official Rust image as the base
FROM rust:latest

# Copy your Rust project into the container
WORKDIR /usr/src/myapp
COPY . .

# Build your Rust application
RUN cargo install --path .

# Add a command to run your application
CMD ["./target/release/emulated_client"]
