version: '3'

services:
  emulated_sr:
    build: ./emulated_sr
    ports:
      - "1234-1345:1234-1345"
    networks:
      - infranet
    hostname: emulated_sr
    container_name: emulated_sr
    depends_on:
      - ctrl_plane
    env_file:
      - .env
  
  ctrl_plane:
    build: ./ctrl_plane
    ports: 
      - "8000:8000"
    hostname: ctrl_plane
    container_name: ctrl_plane
    networks:
      - infranet
    env_file:
      - .env

  client_emulator:
    build: ./client_emulator
    networks:
      - infranet
    depends_on:
      - ctrl_plane
      - emulated_sr
    hostname: client_emulator
    container_name: client_emulator
    env_file:
      - .env


  prometheus:
    build: ./monitor/Prometheus
    volumes:
      - ./monitor/Prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitornet
    depends_on:
      - emulated_sr
      - ctrl_plane
      - cadvisor

  cadvisor:
    build: ./monitor/cAdvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "8080:8080"
    networks:
      - monitornet

networks:
  infranet:
  monitornet:
