FROM prom/prometheus

# Set the working directory inside the container
WORKDIR /etc/prometheus

# Copy the configuration file into the container
#COPY . .

# Specify the command to run on container start
#CMD ["--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus"]

ENTRYPOINT [ "prometheus", \
             "--config.file=/etc/prometheus/prometheus.yml", \
             "--storage.tsdb.path=/prometheus"]
            #  "--storage.tsdb.retention=365d", \
            #  "--web.console.libraries=/usr/share/prometheus/console_libraries", \
            #  "--web.console.templates=/usr/share/prometheus/consoles", \
            #  "--web.external-url=http://localhost:9090", \
            #  "--log.level=info", \
            #  "--log.format=logger:stderr" ] 
